name: ci_meson

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup build/
      env:
        CC: gcc
    - run: ninja -C build
    - run: bash test/test_all.sh

  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install gcc
    - run: pip install meson ninja
    - run: meson setup build/
      env:
        CC: gcc
    - run: ninja -C build
    - run: bash test/test_all.sh
