name: ci_meson

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup build/
      env:
        CC: gcc
    - run: ninja -C build
    - run: bash test/test_all.sh debug
    - run: bash test/test_all.sh release

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: brew install gcc
    - run: pip install meson ninja
    - run: meson setup build/
      env:
        CC: gcc
    - run: ninja -C build
    - run: bash test/test_all.sh debug
    - run: bash test/test_all.sh release
